#include "PAZCryptoAlgorithm.h"

/*
This function encrypts the msg given by random key generated by PAZ algorithm
input: message to encrypt
output: buffer after encryption
*/
Buffer PAZCryptoAlgorithm::Encrypt(const std::string& msg)
{
	Buffer result;
	lastIdxKey = 0;
	for (int i = 0; i < KEY_LEN; i++)
		key.push_back(CHARS[rand() % CHARS_SIZE]);
	for (unsigned int i = 0; i < msg.size(); i++)
	{
		int sum = ((int)msg[i] + (int)key[i % key.size()]) % MAX_CHAR_VAL;
		result.buffer.push_back((unsigned char)sum);
	}
	return result;
}

/*
This function decrypts the msg given by random key generated by PAZ algorithm
input: Buffer to decrypt
output: string after encryption
*/
std::string PAZCryptoAlgorithm::Decrypt(Buffer msg)
{
	std::string result = "";
	for (unsigned int i = 0;  i < msg.buffer.size(); lastIdxKey++, i++)
	{
		int dif = ((int)msg.buffer[i] - (int)key[lastIdxKey % key.size()]) % MAX_CHAR_VAL;
		result.push_back((char)dif);
	}
	return result;
}

//returns the key
std::string PAZCryptoAlgorithm::GetKey()
{
	return key;
}
